# Base configs
baseurl: "/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/fulls"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Anime by FA"
subtitle: "See the world through my eyes!!!!!"
author: "Fallen Angel"
header:
 title: "Photography"
 subtitle: "by FA"
footer:
 name: "Hey there, my name is FA"
 bio: "I am a developer and a FA from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
web_design: "FA"
